version: 2
updates:
# Maintain dependencies for GitHub Actions
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
    time: "06:00"
    timezone: "America/Toronto"
  open-pull-requests-limit: 99
  commit-message:
    prefix: "build: "
- package-ecosystem: "pip"
  directory: "/"
  schedule:
    interval: weekly
  commit-message:
    prefix: "build: "

